# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recept.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='recept.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0crecept.proto\"*\n\nIngredient\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x02\"7\n\x06Recept\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1f\n\ningedients\x18\x02 \x03(\x0b\x32\x0b.Ingredient\")\n\rCocktailSetup\x12\x18\n\x07liquids\x18\x01 \x03(\x0b\x32\x07.Liquid\"\'\n\x06Liquid\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07pump_id\x18\x02 \x01(\x05\x62\x06proto3')
)




_INGREDIENT = _descriptor.Descriptor(
  name='Ingredient',
  full_name='Ingredient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Ingredient.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='Ingredient.amount', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=58,
)


_RECEPT = _descriptor.Descriptor(
  name='Recept',
  full_name='Recept',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Recept.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ingedients', full_name='Recept.ingedients', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=115,
)


_COCKTAILSETUP = _descriptor.Descriptor(
  name='CocktailSetup',
  full_name='CocktailSetup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='liquids', full_name='CocktailSetup.liquids', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=158,
)


_LIQUID = _descriptor.Descriptor(
  name='Liquid',
  full_name='Liquid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Liquid.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pump_id', full_name='Liquid.pump_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=199,
)

_RECEPT.fields_by_name['ingedients'].message_type = _INGREDIENT
_COCKTAILSETUP.fields_by_name['liquids'].message_type = _LIQUID
DESCRIPTOR.message_types_by_name['Ingredient'] = _INGREDIENT
DESCRIPTOR.message_types_by_name['Recept'] = _RECEPT
DESCRIPTOR.message_types_by_name['CocktailSetup'] = _COCKTAILSETUP
DESCRIPTOR.message_types_by_name['Liquid'] = _LIQUID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ingredient = _reflection.GeneratedProtocolMessageType('Ingredient', (_message.Message,), dict(
  DESCRIPTOR = _INGREDIENT,
  __module__ = 'recept_pb2'
  # @@protoc_insertion_point(class_scope:Ingredient)
  ))
_sym_db.RegisterMessage(Ingredient)

Recept = _reflection.GeneratedProtocolMessageType('Recept', (_message.Message,), dict(
  DESCRIPTOR = _RECEPT,
  __module__ = 'recept_pb2'
  # @@protoc_insertion_point(class_scope:Recept)
  ))
_sym_db.RegisterMessage(Recept)

CocktailSetup = _reflection.GeneratedProtocolMessageType('CocktailSetup', (_message.Message,), dict(
  DESCRIPTOR = _COCKTAILSETUP,
  __module__ = 'recept_pb2'
  # @@protoc_insertion_point(class_scope:CocktailSetup)
  ))
_sym_db.RegisterMessage(CocktailSetup)

Liquid = _reflection.GeneratedProtocolMessageType('Liquid', (_message.Message,), dict(
  DESCRIPTOR = _LIQUID,
  __module__ = 'recept_pb2'
  # @@protoc_insertion_point(class_scope:Liquid)
  ))
_sym_db.RegisterMessage(Liquid)


# @@protoc_insertion_point(module_scope)
