/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Sun Jun 30 19:41:44 2019. */

#include "recept.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Ingredient_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, Ingredient, name, name, 0),
    PB_FIELD(  2, FLOAT   , SINGULAR, STATIC  , OTHER, Ingredient, amount, name, 0),
    PB_LAST_FIELD
};

const pb_field_t Recept_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, Recept, name, name, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, CALLBACK, OTHER, Recept, ingedients, name, &Ingredient_fields),
    PB_LAST_FIELD
};

const pb_field_t CocktailSetup_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, CocktailSetup, liquids, liquids, &Liquid_fields),
    PB_LAST_FIELD
};

const pb_field_t Liquid_fields[3] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, Liquid, name, name, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, Liquid, pump_id, name, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(CocktailSetup, liquids[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Ingredient_Recept_CocktailSetup_Liquid)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(CocktailSetup, liquids[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Ingredient_Recept_CocktailSetup_Liquid)
#endif


/* @@protoc_insertion_point(eof) */
